version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: sumukhbhoopalam/frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8000/api/shoppingItems"
    depends_on:
      - backend
      - backenddotnet
    networks:
      - app-network

  backend:
    image: sumukhbhoopalam/backend:latest
    container_name: backend
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - app-network

  backenddotnet:
    build:
      context: ./backend-dotnet
      dockerfile: Dockerfile
    image: sumukhbhoopalam/backenddotnet:latest
    container_name: backenddotnet
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: app-network