version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: sumukhbhoopalam/frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: sumukhbhoopalam/backend:latest
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
